### ISSUE TITLE
[BUG] Forced hammers can appear twice

### ISSUE THREAD

**Issue by Museus** [ellomenop/HadesSpeedrunningMod#28]
If you force Flurry Jab/Double Edge for Achilles/Nemesis they can be offered twice in one hammer

Probably Caused By: Hammer naturally rolling forced hammer and also being forced
Suggested Fix: Remove forced hammers from pool of eligible hammers

**Comment by ellomenop** [comment]
Was this observed on v0.3? I assumed that either this should have been fixed along with the achilles / nemesis fix or it's not coming from the fixed hammers mod

**Comment by Museus** [comment]
It may have been fixed, but for some reason I thought I saw it happen on someone's stream yesterday. I'll close it if I don't see it happen again in the next couple days

**Comment by Museus** [comment]
https://clips.twitch.tv/PeacefulFairRhinocerosHumbleLife-zVYX_DE3dHcJmMlo
@ellomenop it's still happening on latest version

**Comment by Museus** [comment]
Closed by the inclusion of RunStartControl
